### ISSUE TITLE
Octopus card Years [QUESTION]

### ISSUE THREAD

**Issue by WingCH** [metrodroid/metrodroid#635]
Base on your document about [Octopus](https://github.com/metrodroid/metrodroid/wiki/Octopus)

> cards allow a negative balance of up to 50 HKD (previously 35 HKD). This results in the balance being encoded differently.

How do I know when the card was released by programming?

Thanks to your help!

**Comment by micolous** [comment]
The answer is I don't actually know, but I cheat. :)

Metrodroid reads cards and then saves a copy of the (accessible) card data. It also adds some metadata about when that copy was made.  For Octopus, if this scan was created before 2017-10-01, we offset by 35 HKD.  If this scan was created on or after 2017-10-01, we offset by 50 HKD (but I noticed we actually got this wrong, and this will be fixed by #638).

I assume (based on [Octopus FAQ](https://www.octopus.com.hk/en/consumer/customer-service/faq/get-your-octopus/about-octopus.html#3532)) that this change was handled by rewriting the balance field next time the card is used with an Octopus ticket validator.

I prioritise getting this right for folks who are frequently using their Octopus card -- at worst, the balance will be shown 15 HKD _lower_ until the next time they use it in the Octopus system.

**Comment by micolous** [comment]
I have updated and included this explanation in the Wiki now: https://github.com/metrodroid/metrodroid/wiki/Octopus

**Comment by alvinhochun** [comment]
> I assume (based on [Octopus FAQ](https://www.octopus.com.hk/en/consumer/customer-service/faq/get-your-octopus/about-octopus.html#3532)) that this change was handled by rewriting the balance field next time the card is used with an Octopus ticket validator.

For the sake of documentation, I want to clarify that this is not true. Old cards issued before that date will forever have a minimum balance of $-35, no updates are done to them. ([relevant FAQ entry](https://www.octopus.com.hk/en/consumer/customer-service/faq/get-your-octopus/about-octopus.html#3532))

As old cards are gradually being phased out, we can estimate that all (*edit*: on-loan) cards that have a minimum balance of $-35 should be inactive by... the year 2035.

(In contrast, the upgrade of maximum balance from $1000 to $3000 on 2019-12-01 was [seamlessly applied to all cards](https://www.octopus.com.hk/en/consumer/octopus-cards/upgrade-limit/about/index.html).)

**Comment by alvinhochun** [comment]
Sorry, I just realized I made a terrible omission:

The $-50 minimum balance is only applicable to **On-Loan** Octopus and various mobile Octopus. Any Octopus cards that are **sold** (e.g. limited editions, Tourist Octopus, "Octopus – China T-Union Card") will still always have a minimum balance of $-35. (The reason being that they are actually sold for less than $50, so allowing them to get to $-50 would yield the company a loss.)
