### ISSUE TITLE
[BUG] New MyWay card is unrecognised

### ISSUE THREAD

**Issue by pl4nty** [metrodroid/metrodroid#749]
I got a new MyWay card ([image](https://www.flywithme.net.au/wp-content/uploads/2020/09/2020-09-20-23.20.07-720x380.jpg)) in early 2020, and it's only recognised as a fully-locked Mifare Classic, with MyWay/SmartRider fallback enabled. Possibly the standard keys have changed?

My proxmark says it's a hardened Mifare Classic 1k, with no keys in `mfc_default_keys.dic`. I can try and get some sniffed transactions, but I barely use the card so might take a couple weeks.

- Name of the card type: MyWay
- Name of the transit agency: Transport Canberra
- Location: Canberra

- Metrodroid version: 3.0.0
- Device Model: AC2003
- Manufacturer: OnePlus
- Android version: 11 (RP1A.201005.001)
- NFC: On
- MIFARE Classic: Supported

**Comment by micolous** [comment]
If you don't have the keys for a fully-locked card, it will not be recognised as anything.

In the case of SmartRider and MyWay, detection works only if you've loaded one of those "standard" keys.  Metrodroid checks a hash of which keys were used to read the card, because that was the most reliable way to detect a SmartRider or MyWay card, without actually shipping the keys themselves.

There are many different keyfiles around the internet, some contain more keys than others. In any case, [you'll need to crack _your card specifically_ to get any useful data](https://github.com/metrodroid/metrodroid/wiki/Cracking-keys).

As far as I'm aware, the "standard keys" haven't ever changed, so if you ask a friend with an older card, you may be able [to crack that card](https://github.com/metrodroid/metrodroid/wiki/Cracking-keys) to get the standard key, and then use an exploit that works with 1 known key to crack your card.

Metrodroid does **not** ship system-specific keys for _any_ MIFARE Classic cards, even where partially or fully static, due to some ticketing vendors and transport operators being particularly sensitive.  This is even though [MIFARE Classic is not recommended by its manufacturer for "any security relevant application"](https://www.mifare.net/en/products/chip-card-ics/mifare-classic/security-statement-on-crypto1-implementations/) as of 2007.
